document.writeln("<style>");
document.writeln("a {color: #42495b;text-decoration: none;} ");
document.writeln(".d-bottom{ font-size: 12px;text-align:center;width:950px; border-top:2px  #CCCCCC solid;margin-top:10px;padding-top:5px;}");
document.writeln(".d-bottom a{ font-size: 12px;text-align:center; line-height:180%;color: #42495b;}");
document.writeln("<\/style>");
document.writeln('<iframe src="http://image.ccidnet.com/nav/aleax_counts.htm" height="0" width="0"></iframe>');
document.writeln("<script language=javascript src=\"http:\/\/image.ccidnet.com\/nav\/count_JS/ccidstat.js\"><\/script>");
document.writeln('<iframe src="http://image.ccidnet.com/ad_files/home_daohang/copyright_20040226_07.htm" height="0" width="0"></iframe>');
document.writeln("<div class=\"d-bottom\">");
document.writeln("	<br><a href=\"http:\/\/www.ccidnet.com\/\" target=\"_blank\">返回主页<\/a> | <a href=\"http:\/\/image.ccidnet.com\/help\/webmap.html\" target=\"_blank\">网站地图<\/a> | <a href=\"http:\/\/image.ccidnet.com\/help\/aboutus.html\" target=\"_blank\">关于我们<\/a> | <a href=\"http:\/\/register.ccidnet.com\/passport\/service\/agreement.htm\" target=\"_blank\">新用户注册<\/a> | <a href=\"http:\/\/search.ccidnet.com\/\" target=\"_blank\">网站检索<\/a> | <a href=\"mailto:ad@staff.ccidnet.com\" target=\"_blank\">联系广告<\/a> | <a href=\"http:\/\/www.ccidnet.com\/hr\/index.html\" target=\"_blank\">招聘精英<\/a>");
document.writeln("<br>联系我们：<a href=\"mailto:webmaster@staff.ccidnet.com\" target=\"_blank\">webmaster@staff.ccidnet.com<\/a> Tel:8610-88558907\/08 ");
document.writeln("<br>广告发布：<a href=\"mailto:ad@staff.ccidnet.com\" target=\"_blank\">ad@staff.ccidnet.com<\/a> Tel:8610-88558945 8610-88558948 ");
document.writeln("<br>方案、案例展示：<a href=\"mailto:project@staff.ccidnet.com\" target=\"_blank\">project@staff.ccidnet.com<\/a> Tel:8610-88558922 ");
document.writeln("<br><a href=\"http:\/\/image.ccidnet.com\/help\/copyright.htm\" target=\"_blank\">Copyright 2000-2011 CCIDnet.All rights reserved.<\/a>  ");
document.writeln("<br><table width=\"200\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:0 auto;width:200px;\">");
document.writeln("  <tr>");
document.writeln("    <td align=\"center\">京ICP000080号 网站-3<\/td>");
document.writeln("    <td><img src=\"http:\/\/www.ccidnet.com\/images\/news\/news_art\/315.gif\" \/><\/td>");
document.writeln("  <\/tr>");
document.writeln("<\/table>");
document.writeln("");
document.writeln("<\/div>");