document.writeln("<script language=\'javascript\'>");
document.writeln("<!--");
document.writeln("var newWindow=null;");
document.writeln("var checkit=false;");
document.writeln("function check(ID1,ID2){");
document.writeln("	for (var i=0;i<form1.answer.length;i++) {");
document.writeln("		if (form1.answer[i].checked) {checkit=true;break}");
document.writeln("	}");
document.writeln("	if(!checkit) {");
document.writeln("		alert(\"请选择你的答案！\");");
document.writeln("		return false;");
document.writeln("	}");
document.writeln("	if(parseInt(ID2)==123){");
document.writeln("		return true;");
document.writeln("	}else{");
document.writeln("		if(GetCookie(\"qid\")==ID1){");
document.writeln("			alert(\'您已经投过票！谢谢！\');");
document.writeln("			return false;");
document.writeln("		}else{");
document.writeln("			SetCookie(\"qid\",ID1);");
document.writeln("			return true;");
document.writeln("		}");
document.writeln("	}");
document.writeln("}");
document.writeln("function windowOpener(loadpos){");
document.writeln("	if(!newWindow||newWindow.closed){");
document.writeln("		newWindow=window.open(loadpos,\'surveywin\',\'toolbar=no,location=no,status=no,menubar=no,scrollbars=yes,resizable=yes,top=50,left=350,width=450,height=280\');");
document.writeln("	}else{");
document.writeln("		newWindow.focus();");
document.writeln("	}");
document.writeln("}");
document.writeln("var never=new Date();");
document.writeln("never.setTime(never.getTime()+60*1000);");
document.writeln("function SetCookie(name,value){");
document.writeln("	var expString=\';expires=\'+never.toGMTString();");
document.writeln("	document.cookie=name+\'=\'+escape(value)+expString;");
document.writeln("}");
document.writeln("function GetCookie(name){");
document.writeln("	var result=null;");
document.writeln("	var myCookie=\' \'+document.cookie+\';\';");
document.writeln("	var searchName=\' \'+name+\'=\';");
document.writeln("	var startOfCookie=myCookie.indexOf(searchName);");
document.writeln("	var endOfCookie;");
document.writeln("	if(startOfCookie!=-1){");
document.writeln("		startOfCookie+=searchName.length;");
document.writeln("		endOfCookie=myCookie.indexOf(\';\',startOfCookie);");
document.writeln("		result=unescape(myCookie.substring(startOfCookie,endOfCookie));");
document.writeln("	}");
document.writeln("	return result;");
document.writeln("}");
document.writeln("\/\/-->");
document.writeln("<\/script>");
document.writeln("")