(function(i,g){var c=i.bShareUtil,k=i.bShareControl,l=g.body,m=g.documentElement;c.createShareBox=function(j,b){var e=i[j];if(e.isLite){var f=g.createElement("div");f.innerHTML='<div id="bsBox" style="display:none;"></div>';l.appendChild(f)}else e.isOpen=!1,e.bsBox=null,e.create=function(){c.loadStyle("#bsBox{z-index:100000001;background:transparent;padding:0;margin:0;border:none;width:"+b.boxWidth+"px;height:"+b.boxHeight+"px;}#bsClose{_overflow:hidden;cursor:pointer;position:absolute;color:#666;font-weight:bold;font-family:Arial,\u5b8b\u4f53,sans-serif;font-size:12px;line-height:normal;}");
var a=g.createElement("div"),d='<div id="bsBox" style="display:none;"><div id="bsClose">X</div><iframe id="bShareFrame" name="bsFrame'+Math.floor(Math.random()*1E3)+'" frameborder="0" scrolling="no" allowtransparency="true" transparency="true"></iframe></div>';a.innerHTML=d;l.appendChild(a);e.bsBox=g.getElementById("bsBox");g.getElementById("bsClose").onclick=function(){e.disappear()}},e.resetBox=function(a,d){b[a]=d},e.show=function(a){e.isOpen?e.disappear():(e.prepare(a),e.load(),e.display())},
e.display=function(){b.position=b.position||0;switch(b.position){case 0:var a=(c.getWH().w-b.boxWidth)/2,d=(c.getWH().h-b.boxHeight)*2/5,h=Math.max(m.scrollTop,l.scrollTop);e.bsBox.style.position=c.isQk()?"absolute":"fixed";e.bsBox.style.left=(a>0?a:0)+"px";e.bsBox.style.top=(c.isQk()?h:0)+(d>20?d:20)+"px";break;case 1:h=c.getElem(g,"a",b.anchor)[e.curb],a=c.getOffset(h).y,d=c.getOffset(h).x,h=h.offsetHeight,e.bsBox.style.position="absolute",e.bsBox.style.left=d+"px",e.bsBox.style.top=a+h+2+"px"}a=
g.getElementById("bsClose");a.style.top=b.closeTop+"px";a.style.right=b.closeRight+"px";a=g.getElementById("bShareFrame");a.style.height=b.boxHeight+"px";a.style.width=b.boxWidth+"px";e.bsBox.style.height=b.boxHeight+"px";e.bsBox.style.width=b.boxWidth+"px";e.bsBox.style.display=""},e.disappear=function(){e.bsBox.style.display="none";e.isOpen=!1},e.initBox=function(){e.create();l.onclick=function(){e.isOpen&&e.disappear()}}};c.loadEngine=function(j){var b=i[j],e=b.config,f=b.params;b.prepare=function(a){var d=
{};typeof a==="object"?d=a:(b.curb=a===void 0?b.curb:a,b.curb>=0&&(d=b.entries[b.curb]||{}));f.url=d.url||f.url||i.location.href;f.title=d.title||f.title||g.title;f.summary=d.summary?c.shortenText(d.summary,110):f.summary||c.getContent();f.lang=f.request_locale=e.lang;f.pics=d.pics||c.getPics();f.pic=d.pic||f.pic;for(var h in d)/(url|title|summary|content)/.test(h)||(f[h]=d[h])};b.share=function(a,d,h){b.prepare(h);b.load(d)&&b.afterLoad&&b.afterLoad(d);c.stopProp(a)};b.stats=function(a,d,h){b.prepare(h);
b.shareStats(d);c.stopProp(a)};b.shareStats=function(a){var d=b.bhost+"/bshare_share_statistics?";d+="site="+a;d+="&url="+c.encode(f.url);d+="&title="+c.encode(f.title);d+="&publisherUuid="+f.publisherUuid;d+="&type="+f.type;c.loadScript(d)};b.view=function(a){if(!k.viewed){k.viewed=!0;var d=b.bhost+"/bshare_view?Callback="+j+".viewcb&";d+="url="+c.encode(a);d+="&h="+c.encode(i.location.hash);d+="&uuid="+f.publisherUuid;e.showShareCount&&(d+="&sc=1");d+=b.bpsCount?"&l="+b.bpsCount:"&l=17";this.isLite&&
(d+="&lite=1");if(g.referrer)a=g.createElement("a"),a.href=g.referrer,d+="&ref="+c.encode(a.host);c.loadScript(d)}};b.click=function(){if(!k.clicked&&(k.clicked=!0,b.preb!==b.curb)){b.preb=b.curb;var a=b.bhost+"/bshare_click?";a+="url="+c.encode(b.params.url);a+="&title="+c.encode(b.params.title);a+="&uuid="+f.publisherUuid;c.loadScript(a)}};b.promote=function(){f.promote=!0;b.resetBox("boxHeight",588);if(e.style===3){if(e.text===b.iL8n.shareText)e.text=b.iL8n.shareTextPromote}else if(e.style!==4&&
e.style!==5){var a=function(a){a.style.position="relative";a.style.overflow="visible";var h=c.isQk()||(g.documentMode?parseInt(g.documentMode,10)===7:c.isIe7);a.style.display=h?"inline":"inline-block";if(h)a.style.zoom="1";c.getElem(a,"div","bsPromo",function(a){a.style.display="block";a.innerHTML=b.iL8n?b.iL8n.promote:"\u5206\u4eab\u6709\u793c"})};c.getElem(g,"a","bshareDiv",function(d){a(d,c.getElem(d,"div","bsPromo")[0])});c.getElem(g,"div","bshare-custom",function(d){var b=g.createElement("div");b.className="bsPromo";
d.insertBefore(b,d.childNodes[0]);a(d,b)})}};b.viewcb=function(a,d,c,f,g,i,j){k.bShareLoad=!0;typeof a==="number"&&b.entries.length<=1&&b.showCount(a>-1?a:0);if(d)b.user=d;if(c&&c.length>0)e.bps=c;g&&!b.isLite&&typeof b.promote==="function"&&b.promote();(d||c)&&typeof b.ready==="function"&&b.ready();i&&b.entries.length<=1&&typeof b.showStatus==="function"&&b.showStatus(i);j&&typeof b.collect==="function"&&b.collect()};b.collect=function(){var a=b.bhost+"/bshare_log_params?uuid="+f.publisherUuid,d;
for(d in b.customization)a+="&"+d+"="+b.customization[d];c.loadScript(a)};b.count=function(a){if(e.showShareCount){var d=b.bhost+"/bshare_share_count?Callback="+j+".showCount";d+="&url="+c.encode(a);c.loadScript(d)}};b.shareCount=function(a,d){/0|2|10/.test(e.style)?a=c.longRound(a):/11/.test(e.style)||(a=c.shortRound(a));var b={cssFloat:"none"};if(j!=="bShareLike")switch(e.style){case 1:b.left="36px";b.color="#fff";b.fontsize="12px";break;case 10:b.left="27px";case 0:case 2:b.fontsize="11px";break;
case 11:b.top="25px",b.fontsize="17px"}if(d){var g=d.style,f;for(f in b)if(f!=="color"||!g.color)g[f]=b[f];d.innerHTML=c.addCommas(a)}else return c.addCommas(a)};b.showCount=function(a){b.counters=a;var d=c.getElem(g,"span","shareCount");if(!d||d.length===0)d=c.getElem(g,"span","BSHARE_COUNT");var h,e;if(typeof a==="number"){for(h=0,e=d.length;h<e;h++)b.shareCount(a,d[h]);c.getElem(g,"span","BSHARE_COUNT",function(d){d.innerHTML=""+b.shareCount(a,null)})}else if(a.length>0){e=a.length;for(h=0;h<e;h++)b.shareCount(a[h],
d[h]);for(h=e-1;h<d.length;h++)b.shareCount(a[e-1],d[h])}};b.updateCounter=function(a){typeof b.counters==="number"?b.counters+=a?-1:1:b.counters[b.curb]+=a?-1:1;b.showCount(b.counters)};c.roundNumber=function(a,b){try{return Math.round(a*Math.pow(10,b))/Math.pow(10,b)}catch(c){return a}};c.longRound=function(a){if(a>999999)return c.roundNumber(a/1E6,2)+"M";else if(a>99999)return c.roundNumber(a/1E3,1)+"K";return a};c.shortRound=function(a){if(a>999999)return c.roundNumber(a/1E6,1)+"M";else if(a>
99999)return c.roundNumber(a/1E3,0)+"K";else if(a>9999)return c.roundNumber(a/1E3,1)+"K";else if(a>999)return c.roundNumber(a/1E3,2)+"K";return a};c.addCommas=function(a){try{a+="";for(var b=a.split("."),c=b[0],e=b.length>1?"."+b[1]:"",b=/(\d+)(\d{3})/;b.test(c);)c=c.replace(b,"$1,$2");return c+e}catch(f){return a}};c.shortenText=function(a,b){a=a||"";return a.length>b?a.substring(0,b)+"...":a};c.getCurrentSelection=function(){var a="";if(i.getSelection)a=i.getSelection().toString();else if(g.getSelection)a=
g.getSelection;else if(g.selection)try{a=g.selection.createRange().text}catch(b){}return a};c.grabTextContent=function(){for(var a="",b=g.getElementsByTagName("p"),e=0,f=b.length;e<f;e++){var i=b[e];if(i.id==="BSHARE_TEXT"||i.className.indexOf("BSHARE_TEXT")!==-1)a+=c.getText(i)}a===""&&c.getElem(g,"meta",null,function(b){var d=b.getAttribute("name");d&&d.toLowerCase()==="description"&&(a=b.getAttribute("content"))});return a};c.getContent=function(){var a=null,b=c.getCurrentSelection();return b?
c.shortenText(b,110):(a===null&&(a=c.grabTextContent()),c.shortenText(a,110))};c.getPics=function(){for(var a="",b=c.getElem(g,"img"),e=0,f=b.length;e<f;e++){var i=b[e];if(!(i.offsetHeight<=119||i.offsetWidth<=119)){if(a.length+i.src.length>=1500)break;a!==""&&(a+="|");a+=i.src}}return a};c.removeUrlHash=function(a){var b=a.indexOf("#");b>0&&(a=a.substr(0,b));return a};c.showClipboardSuccess=function(){alert(b.iL8n.copySuccess)};c.showClipboardUnsupportBrowsertxt=function(a){prompt(b.iL8n.copyTip,
a)};c.copy2Clipboard=function(){try{var a=c.removeUrlHash(f.url),b=f.title+" "+a,e=i.clipboardData;e?(e.clearData(),e.setData("Text",b),c.showClipboardSuccess()):c.showClipboardUnsupportBrowsertxt(b)}catch(g){}};c.add2Printer=function(){i.print()};c.add2Bookmark=function(){if(i.sidebar)i.sidebar.addPanel(f.title,f.url,"");else if(i.chrome)alert(b.iL8n.bookmarkTip);else if(i.external)try{i.external.AddFavorite(f.url,f.title)}catch(a){}else if(i.opera&&i.print)return!0;else alert(b.iL8n.notSupport)}}})(window,
document);
