document.writeln("<style>");
document.writeln("a {color: #42495b;} ");
document.writeln(".nav{ background-color:#666666;margin-top:5px;}");
document.writeln(".nav li{ font-size: 12px;float:left; background:url(http:\/\/www.ccidnet.com\/images\/news\/news_art\/tiao1.jpg) top right no-repeat;height:15px;padding:5px 6px;}");
document.writeln("<\/style>");
document.writeln("<div class=\"nav\">");
document.writeln("	<ul>");
document.writeln("		<li><a href=\"http:\/\/www.ccidnet.com\/\" target=\"_blank\">首页<\/a><\/li>");
document.writeln("		<li><a href=\"http:\/\/news.ccidnet.com\/\" target=\"_blank\">资讯中心<\/a><\/li>");
document.writeln("		<li><a href=\"http:\/\/comm.ccidnet.com\/\" target=\"_blank\">通信产业<\/a><\/li>");
document.writeln("		<li><a href=\"http:\/\/product.ccidnet.com\/\" target=\"_blank\">IT产品<\/a><\/li>");
document.writeln("		<li><a href=\"http:\/\/tech.ccidnet.com\/\" target=\"_blank\">IT技术<\/a><\/li>");
document.writeln("		<li><a href=\"http:\/\/cio.ccidnet.com\/\" target=\"_blank\">信息化<\/a><\/li>");
document.writeln("		<li><a href=\"http:\/\/bbs.ccidnet.com\/\" target=\"_blank\">社区<\/a><\/li>");
document.writeln("		<li><a href=\"http:\/\/blog.ccidnet.com\/\" target=\"_blank\">博客<\/a><\/li>");
document.writeln("		<li> <a href=\"http:\/\/www.ccidreport.com\/\" target=\"_blank\">市场数据 研究报告<\/a> ·<a href=\"http:\/\/education.ccidnet.com\/\" target=\"_blank\">赛迪教育<\/a> ·<a href=\"http:\/\/v.ccidnet.com\/\" target=\"_blank\">虚拟化<\/a> ·<a href=\"http:\/\/product.ccidnet.com\/hpc\/\" target=\"_blank\">HPC<\/a> ·<a href=\"http:\/\/product.ccidnet.com\/datacenter\/\" target=\"_blank\">数据中心<\/a><\/li>");
document.writeln("		<li><a href=\"http:\/\/chat.ccidnet.com\/\" target=\"_blank\">[访谈]<\/a> <a href=\"http:\/\/news.ccidnet.com\/col\/999\/999.html\" target=\"_blank\">[直播]<\/a> <a href=\"http:\/\/register.ccidnet.com\/passport\/myccid\/mystatus\" target=\"_blank\">[直邮]<\/a> <a href=\"http:\/\/consult.ccidnet.com\/\" target=\"_blank\">[调查]<\/a><\/li>");
document.writeln("	<\/ul>");
document.writeln("<\/div>");